version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.6.1
    networks:
      - es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  
  kibana:
    image: kibana:6.6.1
    networks:
      - es
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  es:
